# Stage 1: Base build stage
FROM python:3.13-slim
 
# Create the app directory
RUN mkdir /app
 
# Set the working directory
WORKDIR /app
 
# Set environment variables to optimize Python
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1 

RUN apt-get update \
    && apt-get upgrade -y \
    && apt-get install -y gcc default-libmysqlclient-dev pkg-config python3-dev build-essential \
    && rm -rf /var/lib/apt/lists/*
 
# Upgrade pip and install dependencies
RUN pip install --upgrade pip
 
# Copy the requirements file first (better caching)
COPY requirements.txt /app/

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt
 
RUN useradd -m -r appuser && \
   chown -R appuser /app
 
 
# Copy application code
COPY --chown=appuser:appuser ./flimotech/ .
 
# Set environment variables to optimize Python
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1 
 
# Switch to non-root user
USER appuser
 
# Expose the application port
EXPOSE 8000 
 
# Start the application using Gunicorn
CMD ["gunicorn", "--bind", "0.0.0.0:8000", "--workers", "1","flimotech.wsgi:application"]